name: Team Registration
description: Register your team for the Game Jam
title: "[Team Registration]: Your Team Name"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to register your team for the Game Jam!
  - type: textarea
    id: discord-handle
    attributes:
      label: Discord Handle
      description: Share your Discord handle so others can contact you.
      placeholder: Your Discord handle (e.g. `@l337coder`)
    validations:
      required: true
  - type: textarea
    id: idea-summary
    attributes:
      label: Idea Summary
      description: Give a short summary of your game idea.
      placeholder: Tell us about your game!
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Tell us a bit about yourself and your team.
      placeholder: Share your story!
    validations:
      required: true
  - type: textarea
    id: looking-for-members
    attributes:
      label: Looking for Members
      description: Tell us a bit about what you're looking for.
      placeholder: Need a designer? An engineer? Something else?
